stages:
  - deploy

image: node:latest

before_script:
  - apt-get update -y
  - apt-get install -y nodejs
  - npm install netlify-cli -g

deploy:
  stage: deploy
  environment:
    name: production
    url: $URL_PRODUCTION
  only:
    - main
  script:
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod --dir=public 